### ISSUE TITLE
Only one CopertStrategy

### ISSUE THREAD

**Issue by twollnik** [twollnik/YETI#25]
Currently the CopertColdStrategy calculates both hot and cold emissions, so the name CopertColdStrategy is misleading.

We should only have one CopertStrategy. In the config file the user can specify whether to include all emissions, or only hot.

**Comment by twollnik** [comment]
@JoanaLeitao How would you prioritize this task?

**Comment by JoanaLeitao** [comment]
I got the feeling from the last meeting that it is important not only for me but for the others to have this in a sensible way.
however i understand that there's some conditionals here because it's not just an item on the config file and it will depend on pollutant... but it should be flexible enough to provide combinations.
so maybe the easiest is:
pollutant: X 
hot:  yes/no
strategy hot: copert/hbefa
cold: yes/no
#be aware that cold emissions are not calculated to all pollutants - check docs
strategy cold: copert/hbefa

if pollutant X is not within the cold possibilities write a warning message also in output run_info that cold emissions not calculated - strategy does not perform for it

if it's hot yes cold no - then output is just hot;
hot no and cold yes - then output is just cold 
with note that in case of copert hot ef were used, 
both yes then total can also be provided but this is not essential in my view

could this be implemented? makes sense? can it just be built on what it's already implemented? too complex? the hot ef is never saved right? so no way to save time there in processing I guess.

if this is too complex then we just have to find a way around it to make the process simple and still be logic/clear to the user ;)

**Comment by twollnik** [comment]
@JoanaLeitao Thank you for the precise answer. I really like it and think that it makes a lot of sense.

I have one question:
What do we do with calculation methods that don't have these two stages? For example the PMNonExhaustStrategy does not have a hot-cold division.

Regarding the implementation complexity:
This is feasable for sure but would require large changes both to the code and to the docs. If we prioritize this, I am not sure that I will have time to do all the other things on our priority list.

A quicker solution would be to merge the CopertColdStrategy and the CopertHotStrategy into one CopertStrategy that takes a parameter `only_hot`. Would this be an option for you?

**Comment by JoanaLeitao** [comment]
@twollnik only hot would do what exactly?
merging sounds good in any case

PMNonExhaust is addition to all Exhaust Emissions - so should be as it is an additional strategy - not sure if I answered your question

**Comment by twollnik** [comment]
> only hot would do what exactly?

If `only_hot: yes` is given in the config file YETI would only calculate hot emissions, not cold.

-------

Regarding the PM non exhaust strategy:

You suggest a config layout such as
```yaml
hot:            yes/no
strategy_hot:   copert/hbefa
cold:           yes/no
#be aware that cold emissions are not calculated to all pollutants - check docs
strategy_cold:  copert/hbefa
```
I am wondering how a user would specify that they want to use the PMNonExhaustStrategy. Would they set the `strategy_hot` to PMNonExhaustStrategy?

**Comment by JoanaLeitao** [comment]
Ah I see!
Only hot parameter sounds good - but that with cold accounted would be either copert hot & copert cold OR hbefa hot & hbefa cold?

In that case I guess the options in the config would be?
pollutant: X
exhaust: yes/no
#only PM is non-exhaust
strategy: copert/hbefa
only hot: yes/no
#cold emissions determined with strategy defined above 
(assuming we implement cold hbefa soon)
makes sense?

**Comment by twollnik** [comment]
In the interest of time I would suggest to leave the config layout mostly as is. What we could do is:

```yaml
pollutant:      X
strategy:       CopertStrategy
only_hot:       no
hot_strategy:   HbefaHotStrategy # optional parameter if you want to use a different hot strategy
```

Is this okay?

**Comment by JoanaLeitao** [comment]
but at some point there will be 2 colds no?
so "strategy" here is hot&cold doing either both copert or both hbefa? and if it's only hot then either copert or hbefa can be selected?

**Comment by twollnik** [comment]
Not exactly. The idea is that we may still want to have a single `strategy` parameter because there are strategies (like PMNonExhaust) that can't be split into hot/cold calculation. As `strategy` we chose the strategy we want to use for cold emission. *If* the user wants to use a different hot than cold strategy, he/she can "override" the hot strategy using the `hot_strategy` parameter.

Say the user want to use copert hot and copert cold:
```yaml
pollutant:      X
strategy:       CopertStrategy
```
If he/she want to use copert cold and hbefa hot:
```yaml
pollutant:      X
strategy:       CopertStrategy
hot_strategy:   HbefaHotStrategy # optional parameter if you want to use a different hot strategy
```
If he/she wants only hbefa hot emissions:
```yaml
pollutant:      X
strategy:       HbefaStrategy
only_hot:       yes
```

Does this make it clear?

**Comment by JoanaLeitao** [comment]
well I see the point of the PM_NonExhaust - but there there's really not an option... at least not at the moment and I don't think there will be before you're done.
So by default it can only be that one that is implemented so I was not putting into the picture.

I thinking calling it "strategy" and then "hot strategy" being something else it's just contradicting/missleading no? because then it means that the "strategy" define in first option is just method for cold emissions .. and then we're down to what we sort of have already.
So why not the other way around:
```yaml
strategy = hot calculations # by default all pollutants have at least
# cold can be overwritten to be something else
pollutant:      X
strategy:       CopertStrategy
```

If he/she want to use copert HOT and hbefa COLD:
```yaml
pollutant:      X
strategy:       CopertStrategy
COLD_strategy:  HbefaCOLDStrategy # optional parameter if you want to use a different hot strategy
```

If he/she wants only hbefa hot emissions:
```yaml
pollutant:      X
strategy:       HbefaStrategy
only_hot:       yes
 ```
or is this more difficult to implement?

**Comment by twollnik** [comment]
> and sorry that I don't do the nice fancy easy reading formatting as you have ;) 

I fixed it for you :)

Your suggestion is much better than mine, let's do it like that!

**Comment by twollnik** [comment]
## Implementation notes

### Goal
Implement the `CopertStrategy`. A Strategy that calculates hot emissions using the copert methodology and can use an arbitrary other Strategy to calculate cold emission.

### Usage
**Case only hot emissions**: Only hot emissions should be calculated
```yaml
strategy:    code.[..].CopertStrategy
only_hot:    yes
[..] # other args just like for CopertHotStrategy
```

**Base case hot&cold**: use copert cold
```yaml
strategy:            code.[..].CopertStrategy
[..] # other args just like for CopertColdStrategy
```
**Advanced case hot&cold**: use a different cold strategy
```yaml
strategy:          code.[..].CopertStrategy
cold_strategy:     code.[..].ColdStrategy
cold_load_berlin_format_data_function: path.to.load_function
cold_load_yeti_format_data_function: path.to.load_function
cold_validation_function: path.to.validation_function
[...] #all args for CopertHotStrategy are required
[...] # any additional args for the ColdStrategy should also be included 
```
### Naming conflicts
.. are a possible issue. For example `berlin_format_emission_factors` is a config argument for the `CopertHotStrategy` and for the `HbefaColdStrategy`, however the two Strategies require input data in a different format. 
Solution: whenever a naming conflict arises, prefix the argument that should go to the `CopertHotStrategy` with `hot_[..]`. Prefix the argument that should go to the `ColdStrategy` with `cold_[..]`.
In our example for `berlin_format_emission_factors` we would add these lines to the config:
```yaml
hot_berlin_format_emission_factors:   path/to/ef_data_for_hot_strategy.csv
cold_berlin_format_emission_factors:   path/to/ef_data_for_cold_strategy.csv
```
### Output
The normal output of the Strategies used. Files are prefixed `hot_[..]` or `cold_[..]`.

### Checklist
- [x] `load_berlin_format_data_function` for CopertStrategy
- [x] `load_yeti_format_data_function` for CopertStrategy
- [x] `CopertStrategy`
- [x] add acceptance test that checks if calculations are correct. (Actually looks at the output data)
- [x] handle the case that the cold_strategy also calculates hot emissions (don't calculate and output the hot emissions twice) -> DISCARDED: mention in docs, that if CopertColdStrategy is to be used, users shouldn't pass it as cold_strategy. 
- [x] docs page for CopertStrategy
- [x] example config file (using `cold_strategy:    code.[..].HbefaColdStrategy)
- [x] `validation_function` for CopertStrategy -> DISCARDED: mention in docs that validation functions for other Strategies can be used in most cases.
- [x] class comment for CopertStrategy
- [x] fix run_info.txt file for CopertStrategy
- [x] add option `fixed_speed` to CopertStrategy
